name: mixed
dataset:
  seta: benchmarks/seta_env_convert/train.jsonl
  safety: benchmarks/agent_safetybench_convert/train.jsonl
  agentharm: benchmarks/agentharm_convert/train.jsonl
ratios:
  seta: 6
  safety: 2
  agentharm: 2
max_turn: 10
