# Optional Python environment containing transformer_engine + sglang. Leave
# unset to use the caller's PATH; site launchers can provide an absolute path.
LIGHTRFT_PY312_BIN="${LIGHTRFT_PY312_BIN:-}"
if [[ -n "${LIGHTRFT_PY312_BIN}" ]]; then
  export PATH="${LIGHTRFT_PY312_BIN}:${PATH}"
fi
DRY_RUN="${DRY_RUN:-0}"

# ── Cleanup previous processes ───────────────────────────────────────
if [[ "${DRY_RUN}" == "1" ]]; then
  log "DRY_RUN=1: skipping process cleanup and Ray startup"
else
  pkill -9 sglang || true
  sleep 2
  ray stop --force || true
  pkill -9 ray || true
  pkill -9 -f "agentic_rl.platform.router_cli" || true
  sleep 2
fi

export PYTHONUNBUFFERED=1
export PYTHONFAULTHANDLER=1

# ── GPU allocation (auto-split: half actor, half rollout) ────────────
if command -v nvidia-smi >/dev/null 2>&1; then
  DETECTED_GPUS="$(nvidia-smi -L 2>/dev/null | grep -c '^GPU ' || true)"
else
  DETECTED_GPUS=0
fi
if [[ "${DETECTED_GPUS}" -le 0 ]]; then
  DETECTED_GPUS=4
fi
NUM_GPUS="${NUM_GPUS:-${DETECTED_GPUS}}"
HALF_GPUS=$(( NUM_GPUS / 2 ))
# Default: each gets half of available GPUs (4-GPU node → 2/2, 8-GPU → 4/4).
# Important: matching node size avoids SIGSEGV in NCCL getenv() observed when
# only a subset of GPUs are used on multi-NUMA 8-GPU nodes.
ACTOR_GPUS="${ACTOR_GPUS:-${HALF_GPUS}}"
ROLLOUT_GPUS="${ROLLOUT_GPUS:-${HALF_GPUS}}"
ROLLOUT_NUM_GPUS_PER_ENGINE="${ROLLOUT_NUM_GPUS_PER_ENGINE:-${HALF_GPUS}}"
TP_SIZE="${TP_SIZE:-${ACTOR_GPUS}}"

if (( ACTOR_GPUS + ROLLOUT_GPUS > NUM_GPUS )); then
  echo "ACTOR_GPUS(${ACTOR_GPUS}) + ROLLOUT_GPUS(${ROLLOUT_GPUS}) > NUM_GPUS(${NUM_GPUS})"
  exit 1
fi
log "GPU config: total=${NUM_GPUS}, actor=${ACTOR_GPUS}, rollout=${ROLLOUT_GPUS}, TP=${TP_SIZE}, engine_tp=${ROLLOUT_NUM_GPUS_PER_ENGINE}"



# Qwen3-8B remains the compatibility default; examples may override all model fields.
MODEL_TAG="${MODEL_TAG:-qwen3-8b}"
MODEL_DISPLAY_NAME="${MODEL_DISPLAY_NAME:-${MODEL_TAG}}"
MODEL_ARGS_FILE="${MODEL_ARGS_FILE:-qwen3-8B}"
HF_CKPT="${HF_CKPT:-${REPO_ROOT}/models/Qwen3-8B}"
REF_LOAD="${REF_LOAD:-${REPO_ROOT}/models/Qwen3-8B_torch_dist}"

EXPORT_ROOT="${EXPORT_ROOT:-${REPO_ROOT}/export}"

RUN_TIMESTAMP="${RUN_TIMESTAMP:-$(date +%F_%H%M%S)}"
DEBUG_MODE="${DEBUG_MODE:-0}"
# Defaults needed early so the run directory name carries the key experiment
# identity. Dataset construction and full validation still happen below.
ALGO="${ALGO:-dapo}"
case "${ALGO}" in
  grpo|dapo) ;;
  *)
    echo "[ERROR] Unknown ALGO=${ALGO}. Use: grpo|dapo"
    exit 1
    ;;
esac
export ALGO
DATASET="$(normalize_dataset "${DATASET:-mixed}")"
case "${DATASET}" in
  seta|safety|agentharm|mixed|swesmith) ;;
  *)
    echo "[ERROR] Unknown DATASET=${DATASET}. Use: seta|safety|agentharm|mixed|swesmith"
    exit 1
    ;;
esac
if [[ "${DATASET}" == "swesmith" ]]; then
  export ENSURE_IMAGE_TIMEOUT="${ENSURE_IMAGE_TIMEOUT:-1800}"
  export RESET_SESSION_TIMEOUT="${RESET_SESSION_TIMEOUT:-900}"
  export CLOSE_SESSION_TIMEOUT="${CLOSE_SESSION_TIMEOUT:-90}"
  export EVAL_TIMEOUT="${EVAL_TIMEOUT:-1200}"
  export ROUTER_FORWARD_TIMEOUT="${ROUTER_FORWARD_TIMEOUT:-5100}"
fi
HARNESS_OPTION="${HARNESS_OPTION:-camel-agent}"
case "${HARNESS_OPTION}" in
  camel-agent|camel_agent)
    HARNESS_OPTION="camel-agent"
    ;;
  claude-code|claude_code)
    HARNESS_OPTION="claude-code"
    ;;
  *)
    echo "[ERROR] Unknown HARNESS_OPTION=${HARNESS_OPTION}. Use: camel-agent|claude_code"
    exit 1
    ;;
esac
SETA_SAFETY="${SETA_SAFETY:-none}"
SAFETY_BENCH_REWARD="${SAFETY_BENCH_REWARD:-dense_rule}"
AGENTHARM_REWARD="${AGENTHARM_REWARD:-dense_rule}"
SAFETY_REWARD_COEF="${SAFETY_REWARD_COEF:-0}"
MIX_SETA_RATIO="${MIX_SETA_RATIO:-6}"
MIX_SAFETY_RATIO="${MIX_SAFETY_RATIO:-2}"
MIX_AGENTHARM_RATIO="${MIX_AGENTHARM_RATIO:-2}"
MIX_MODE="${MIX_MODE:-all_visible}"
MAX_TURN="${MAX_TURN:-10}"
DAPO_EPS_CLIP_HIGH="${DAPO_EPS_CLIP_HIGH:-0.28}"
DAPO_CALCULATE_PER_TOKEN_LOSS="${DAPO_CALCULATE_PER_TOKEN_LOSS:-1}"
DAPO_DYNAMIC_SAMPLING="${DAPO_DYNAMIC_SAMPLING:-0}"

# Exploration defaults are defined in the main script as well as the wrapper so
# direct invocations remain stable under `set -u`, and Ray runtime_env can always
# receive explicit values. Bug fix: previously the exploration wrapper exported
# EXPLORE_* in the parent shell, but ray job submit workers only received the
# hand-built RUNTIME_ENV_JSON below, so generate.py often saw all exploration
# switches as disabled.
EXPLORATION_PROFILE="${EXPLORATION_PROFILE:-${EXPLORE_PROFILE:-off}}"
EXPLORE_ENTROPY_COEF="${EXPLORE_ENTROPY_COEF:-0.0}"
EXPLORE_THINK_MODE="${EXPLORE_THINK_MODE:-1}"
EXPLORE_TEMP_HIGH="${EXPLORE_TEMP_HIGH:-}"
EXPLORE_INTRINSIC="${EXPLORE_INTRINSIC:-0}"
EXPLORE_INTRINSIC_ENABLED="${EXPLORE_INTRINSIC_ENABLED:-${EXPLORE_INTRINSIC}}"
EXPLORE_INTRINSIC_COEF="${EXPLORE_INTRINSIC_COEF:-0.1}"
EXPLORE_INTRINSIC_SCHEDULE="${EXPLORE_INTRINSIC_SCHEDULE:-constant}"
EXPLORE_INTRINSIC_DECAY_STEPS="${EXPLORE_INTRINSIC_DECAY_STEPS:-0}"
EXPLORE_INTRINSIC_REDUCER="${EXPLORE_INTRINSIC_REDUCER:-sum}"
EXPLORE_INTRINSIC_GRANULARITY="${EXPLORE_INTRINSIC_GRANULARITY:-raw}"
EXPLORE_INTRINSIC_SCOPE="${EXPLORE_INTRINSIC_SCOPE:-process}"
EXPLORE_SCORE_BONUS_COMPONENTS="${EXPLORE_SCORE_BONUS_COMPONENTS:-legacy}"
EXPLORE_SAFETY_FILTER="${EXPLORE_SAFETY_FILTER:-0}"
EXPLORE_SAFETY_FILTER_ENABLED="${EXPLORE_SAFETY_FILTER_ENABLED:-${EXPLORE_SAFETY_FILTER}}"
EXPLORE_SAFETY_FILTER_COEF="${EXPLORE_SAFETY_FILTER_COEF:--0.5}"
EXPLORE_LPRND="${EXPLORE_LPRND:-0}"
EXPLORE_LPRND_ENABLED="${EXPLORE_LPRND_ENABLED:-${EXPLORE_LPRND}}"
EXPLORE_LPRND_COEF="${EXPLORE_LPRND_COEF:-0.05}"
EXPLORE_LPRND_SCHEDULE="${EXPLORE_LPRND_SCHEDULE:-constant}"
EXPLORE_LPRND_DECAY_STEPS="${EXPLORE_LPRND_DECAY_STEPS:-0}"
EXPLORE_LPRND_CLIP="${EXPLORE_LPRND_CLIP:-3.0}"
EXPLORE_LPRND_WARMUP="${EXPLORE_LPRND_WARMUP:-32}"
EXPLORE_AGENT57_LITE="${EXPLORE_AGENT57_LITE:-0}"
EXPLORE_AGENT57_LITE_ENABLED="${EXPLORE_AGENT57_LITE_ENABLED:-${EXPLORE_AGENT57_LITE}}"
EXPLORE_AGENT57_K="${EXPLORE_AGENT57_K:-8}"
EXPLORE_AGENT57_ARM_BETAS="${EXPLORE_AGENT57_ARM_BETAS:-0,0.003,0.006,0.01,0.015,0.02,0.03,0.04}"
EXPLORE_AGENT57_COMBINE_MODE="${EXPLORE_AGENT57_COMBINE_MODE:-add}"
EXPLORE_AGENT57_NGU_MOD_CLIP="${EXPLORE_AGENT57_NGU_MOD_CLIP:-5.0}"
EXPLORE_AGENT57_NGU_EPISODIC_SOURCE="${EXPLORE_AGENT57_NGU_EPISODIC_SOURCE:-signature_intrinsic}"
EXPLORE_AGENT57_NGU_EPISODIC_REDUCER="${EXPLORE_AGENT57_NGU_EPISODIC_REDUCER:-${EXPLORE_INTRINSIC_REDUCER}}"
EXPLORE_AGENT57_NGU_LIFE_MOD_MODE="${EXPLORE_AGENT57_NGU_LIFE_MOD_MODE:-linear}"
EXPLORE_AGENT57_NGU_LIFE_MOD_STD_CLIP="${EXPLORE_AGENT57_NGU_LIFE_MOD_STD_CLIP:-5.0}"
EXPLORE_AGENT57_MAX_BONUS="${EXPLORE_AGENT57_MAX_BONUS:-0}"
EXPLORE_AGENT57_ARM_TEMPERATURES="${EXPLORE_AGENT57_ARM_TEMPERATURES:-}"
EXPLORE_AGENT57_ARM_TEMPERATURE_WARMUP_ROLLOUTS="${EXPLORE_AGENT57_ARM_TEMPERATURE_WARMUP_ROLLOUTS:-0}"
EXPLORE_AGENT57_ARM_TOP_PS="${EXPLORE_AGENT57_ARM_TOP_PS:-}"
EXPLORE_AGENT57_ARM_TOP_KS="${EXPLORE_AGENT57_ARM_TOP_KS:-}"
EXPLORE_AGENT57_CONTROLLER="${EXPLORE_AGENT57_CONTROLLER:-fixed}"
EXPLORE_AGENT57_UCB_C="${EXPLORE_AGENT57_UCB_C:-0.5}"
EXPLORE_AGENT57_UCB_WINDOW="${EXPLORE_AGENT57_UCB_WINDOW:-256}"
EXPLORE_AGENT57_UCB_EPSILON="${EXPLORE_AGENT57_UCB_EPSILON:-0}"
EXPLORE_AGENT57_UCB_MIN_PER_ARM="${EXPLORE_AGENT57_UCB_MIN_PER_ARM:-0}"
EXPLORE_AGENT57_UCB_VALUE="${EXPLORE_AGENT57_UCB_VALUE:-legacy}"
EXPLORE_AGENT57_UCB_DATASET_AWARE="${EXPLORE_AGENT57_UCB_DATASET_AWARE:-0}"
EXPLORE_AGENT57_UCB_RANDOM_SEED="${EXPLORE_AGENT57_UCB_RANDOM_SEED:-}"
EXPLORE_AGENT57_UCB_SEED_SALT="${EXPLORE_AGENT57_UCB_SEED_SALT:-}"
EXPLORE_AGENT57_KEEP_BASELINE="${EXPLORE_AGENT57_KEEP_BASELINE:-1}"
EPISODIC_MEMORY_BACKEND="${EPISODIC_MEMORY_BACKEND:-simhash_knn}"
EXPLORE_AGENT57_EPISODIC_BACKEND="${EXPLORE_AGENT57_EPISODIC_BACKEND:-${EPISODIC_MEMORY_BACKEND}}"
EXPLORE_AGENT57_EPISODIC_CAPACITY="${EXPLORE_AGENT57_EPISODIC_CAPACITY:-4096}"
EXPLORE_AGENT57_EPISODIC_COUNT_DECAY="${EXPLORE_AGENT57_EPISODIC_COUNT_DECAY:-1.0}"
EXPLORE_AGENT57_EPISODIC_CLEAR_ON_RESET="${EXPLORE_AGENT57_EPISODIC_CLEAR_ON_RESET:-1}"
EXPLORE_AGENT57_EPISODIC_SIMHASH_BITS="${EXPLORE_AGENT57_EPISODIC_SIMHASH_BITS:-64}"
EXPLORE_AGENT57_EPISODIC_BUCKET_CAPACITY="${EXPLORE_AGENT57_EPISODIC_BUCKET_CAPACITY:-256}"
EXPLORE_AGENT57_EPISODIC_K="${EXPLORE_AGENT57_EPISODIC_K:-5}"
EXPLORE_AGENT57_EPISODIC_DISTANCE="${EXPLORE_AGENT57_EPISODIC_DISTANCE:-cosine}"
EXPLORE_AGENT57_EPISODIC_VECTOR_DIM="${EXPLORE_AGENT57_EPISODIC_VECTOR_DIM:-256}"
EXPLORE_AGENT57_EPISODIC_RANDOM_SEED="${EXPLORE_AGENT57_EPISODIC_RANDOM_SEED:-}"
EXPLORE_AGENT57_EPISODIC_OBS_MODE="${EXPLORE_AGENT57_EPISODIC_OBS_MODE:-fingerprint}"
EXPLORE_AGENT57_EPISODIC_INCLUDE_TURN="${EXPLORE_AGENT57_EPISODIC_INCLUDE_TURN:-1}"
EXPLORE_AGENT57_EPISODIC_TURN_MODE="${EXPLORE_AGENT57_EPISODIC_TURN_MODE:-bucket}"
EXPLORE_AGENT57_EPISODIC_MULTI_PROBE_RADIUS="${EXPLORE_AGENT57_EPISODIC_MULTI_PROBE_RADIUS:-1}"
EXPLORE_AGENT57_EPISODIC_NOVELTY_FLOOR="${EXPLORE_AGENT57_EPISODIC_NOVELTY_FLOOR:-0.05}"
EXPLORE_AGENT57_LIFELONG="${EXPLORE_AGENT57_LIFELONG:-0}"
EXPLORE_AGENT57_LIFELONG_ENABLED="${EXPLORE_AGENT57_LIFELONG_ENABLED:-${EXPLORE_AGENT57_LIFELONG}}"
EXPLORE_AGENT57_LIFELONG_COEF="${EXPLORE_AGENT57_LIFELONG_COEF:-0.01}"
EXPLORE_AGENT57_LIFELONG_CLIP="${EXPLORE_AGENT57_LIFELONG_CLIP:-2.0}"
EXPLORE_AGENT57_LIFELONG_WARMUP="${EXPLORE_AGENT57_LIFELONG_WARMUP:-64}"
EXPLORE_AGENT57_LIFELONG_COUNT_DECAY="${EXPLORE_AGENT57_LIFELONG_COUNT_DECAY:-1.0}"
EXPLORE_AGENT57_LIFELONG_CAPACITY="${EXPLORE_AGENT57_LIFELONG_CAPACITY:-0}"
EXPLORE_AGENT57_LIFELONG_BACKEND="${EXPLORE_AGENT57_LIFELONG_BACKEND:-local}"
EXPLORE_AGENT57_LIFELONG_KEY_VERSION="${EXPLORE_AGENT57_LIFELONG_KEY_VERSION:-v1}"
EXPLORE_AGENT57_LIFELONG_INCLUDE_DATASET="${EXPLORE_AGENT57_LIFELONG_INCLUDE_DATASET:-1}"
EXPLORE_AGENT57_LIFELONG_INCLUDE_TASK="${EXPLORE_AGENT57_LIFELONG_INCLUDE_TASK:-1}"
EXPLORE_AGENT57_LIFELONG_INCLUDE_TURN="${EXPLORE_AGENT57_LIFELONG_INCLUDE_TURN:-0}"
EXPLORE_AGENT57_LIFELONG_OBS_MODE="${EXPLORE_AGENT57_LIFELONG_OBS_MODE:-fingerprint}"
EXPLORE_AGENT57_LIFELONG_HIERARCHICAL="${EXPLORE_AGENT57_LIFELONG_HIERARCHICAL:-1}"
EXPLORE_AGENT57_LIFELONG_TASK_WEIGHT="${EXPLORE_AGENT57_LIFELONG_TASK_WEIGHT:-0.5}"
EXPLORE_AGENT57_LIFELONG_SKILL_WEIGHT="${EXPLORE_AGENT57_LIFELONG_SKILL_WEIGHT:-0.35}"
EXPLORE_AGENT57_LIFELONG_GLOBAL_WEIGHT="${EXPLORE_AGENT57_LIFELONG_GLOBAL_WEIGHT:-0.15}"
EXPLORE_AGENT57_SQLITE_BUSY_TIMEOUT_MS="${EXPLORE_AGENT57_SQLITE_BUSY_TIMEOUT_MS:-30000}"
EXPLORE_AGENT57_SQLITE_WAL="${EXPLORE_AGENT57_SQLITE_WAL:-0}"
EXPLORE_AGENT57_TRUST_GATE="${EXPLORE_AGENT57_TRUST_GATE:-hard}"
EXPLORE_AGENT57_TRUST_COMPLETED="${EXPLORE_AGENT57_TRUST_COMPLETED:-1.0}"
EXPLORE_AGENT57_TRUST_TRUNCATED="${EXPLORE_AGENT57_TRUST_TRUNCATED:-0.3}"
EXPLORE_AGENT57_TRUST_FAILED="${EXPLORE_AGENT57_TRUST_FAILED:-0.1}"
EXPLORE_AGENT57_TRUST_PARSE_ERROR="${EXPLORE_AGENT57_TRUST_PARSE_ERROR:-0.1}"
EXPLORE_AGENT57_TRUST_WARMUP="${EXPLORE_AGENT57_TRUST_WARMUP:-0.3}"
EXPLORE_AGENT57_STATE_PATH="${EXPLORE_AGENT57_STATE_PATH:-}"
EXPLORE_AGENT57_SUCCESS_THRESHOLD="${EXPLORE_AGENT57_SUCCESS_THRESHOLD:-0.0}"
EXPLORE_ADVANTAGE_BONUS="${EXPLORE_ADVANTAGE_BONUS:-0}"
EXPLORE_ADVANTAGE_BONUS_ENABLED="${EXPLORE_ADVANTAGE_BONUS_ENABLED:-${EXPLORE_ADVANTAGE_BONUS}}"
EXPLORE_ADVANTAGE_BONUS_MODE="${EXPLORE_ADVANTAGE_BONUS_MODE:-component}"
EXPLORE_ADVANTAGE_BONUS_COMPONENTS="${EXPLORE_ADVANTAGE_BONUS_COMPONENTS:-explore_intrinsic_scaled}"
EXPLORE_ADVANTAGE_BONUS_COEF="${EXPLORE_ADVANTAGE_BONUS_COEF:-1.0}"
EXPLORE_ADVANTAGE_BONUS_CLIP="${EXPLORE_ADVANTAGE_BONUS_CLIP:-0.5}"
EXPLORE_ADVANTAGE_INTRINSIC_KEY="${EXPLORE_ADVANTAGE_INTRINSIC_KEY:-explore_agent57_intrinsic_signal}"
EXPLORE_ADVANTAGE_LAMBDA="${EXPLORE_ADVANTAGE_LAMBDA:-0.05}"
EXPLORE_ADVANTAGE_LAMBDA_SCHEDULE="${EXPLORE_ADVANTAGE_LAMBDA_SCHEDULE:-constant}"
EXPLORE_ADVANTAGE_LAMBDA_DECAY_STEPS="${EXPLORE_ADVANTAGE_LAMBDA_DECAY_STEPS:-0}"
EXPLORE_ADVANTAGE_ARM_WEIGHT_MODE="${EXPLORE_ADVANTAGE_ARM_WEIGHT_MODE:-normalized_beta}"
EXPLORE_ADVANTAGE_TRUST_KEY="${EXPLORE_ADVANTAGE_TRUST_KEY:-explore_agent57_trust}"
EXPLORE_ADVANTAGE_GATE_MODE="${EXPLORE_ADVANTAGE_GATE_MODE:-legacy}"
EXPLORE_ADVANTAGE_OUTCOME_KEY="${EXPLORE_ADVANTAGE_OUTCOME_KEY:-raw_score}"
EXPLORE_ADVANTAGE_COMPLETED_FLOOR="${EXPLORE_ADVANTAGE_COMPLETED_FLOOR:-0.50}"
EXPLORE_ADVANTAGE_TRUNCATED_FLOOR="${EXPLORE_ADVANTAGE_TRUNCATED_FLOOR:-0.15}"
EXPLORE_ADVANTAGE_FAILED_FLOOR="${EXPLORE_ADVANTAGE_FAILED_FLOOR:-0.0}"
EXPLORE_ADVANTAGE_ABORTED_FLOOR="${EXPLORE_ADVANTAGE_ABORTED_FLOOR:-0.0}"
EXPLORE_ADVANTAGE_TRUNCATED_INTRINSIC_SCALE="${EXPLORE_ADVANTAGE_TRUNCATED_INTRINSIC_SCALE:-1.0}"
EXPLORE_ADVANTAGE_FAILED_INTRINSIC_SCALE="${EXPLORE_ADVANTAGE_FAILED_INTRINSIC_SCALE:-1.0}"
EXPLORE_TRUNCATION_PENALTY="${EXPLORE_TRUNCATION_PENALTY:-0}"
EXPLORE_ADVANTAGE_TRUNCATION_PENALTY="${EXPLORE_ADVANTAGE_TRUNCATION_PENALTY:-${EXPLORE_TRUNCATION_PENALTY}}"
EXPLORE_TRUNCATION_PENALTY_OUTCOME_AWARE="${EXPLORE_TRUNCATION_PENALTY_OUTCOME_AWARE:-0}"
EXPLORE_CDE_ACTOR="${EXPLORE_CDE_ACTOR:-0}"
EXPLORE_CDE_ACTOR_ENABLED="${EXPLORE_CDE_ACTOR_ENABLED:-${EXPLORE_CDE_ACTOR}}"
EXPLORE_CDE_ACTOR_OMEGA="${EXPLORE_CDE_ACTOR_OMEGA:-0.05}"
EXPLORE_CDE_ACTOR_KAPPA="${EXPLORE_CDE_ACTOR_KAPPA:-2.0}"
EXPLORE_CDE_ACTOR_ALPHA="${EXPLORE_CDE_ACTOR_ALPHA:-0.1}"
EXPLORE_CDE_ACTOR_DECAY_STEPS="${EXPLORE_CDE_ACTOR_DECAY_STEPS:-0}"
EXPLORE_CDE_ACTOR_REWARD_GATE="${EXPLORE_CDE_ACTOR_REWARD_GATE:-nonzero}"
EXPLORE_RETRY_ATTEMPTS="${EXPLORE_RETRY_ATTEMPTS:-1}"
EXPLORE_RETRY_TRAJ_GAMMA="${EXPLORE_RETRY_TRAJ_GAMMA:-1.0}"
SLIME_SKIP_ZERO_TRAINABLE_ROLLOUT="${SLIME_SKIP_ZERO_TRAINABLE_ROLLOUT:-0}"
SLIME_SKIP_ZERO_TRAINABLE_TRAIN="${SLIME_SKIP_ZERO_TRAINABLE_TRAIN:-1}"
